# Generated by Django 3.2.5 on 2023-03-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_votingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='title',
            field=models.CharField(choices=[('pr', 'President'), ('vp', 'Vice President'), ('sg', 'Secretary General'), ('vs', 'Vice Secretary General'), ('tr', 'Treasurer'), ('dt', 'Deputy Treasurer'), ('os', 'Organizing Secretary'), ('eas', 'External Relations Secretary'), ('ers', 'Education and Research Secretary'), ('ad', 'Auditor'), ('tru', 'Trustees')], max_length=5),
        ),
    ]
